/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecettesIndexRouteImport } from './routes/recettes.index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as RecettesRecipeSlugRouteImport } from './routes/recettes.$recipeSlug'
import { Route as ProduitsProductIdRouteImport } from './routes/produits.$productId'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRecipesRouteImport } from './routes/dashboard.recipes'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'

const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesIndexRoute = RecettesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecettesRoute,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduitsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const RecettesRecipeSlugRoute = RecettesRecipeSlugRouteImport.update({
  id: '/$recipeSlug',
  path: '/$recipeSlug',
  getParentRoute: () => RecettesRoute,
} as any)
const ProduitsProductIdRoute = ProduitsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProduitsRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecipesRoute = DashboardRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entreprise': typeof EntrepriseRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recettes': typeof RecettesRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/recipes': typeof DashboardRecipesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/produits/$productId': typeof ProduitsProductIdRoute
  '/recettes/$recipeSlug': typeof RecettesRecipeSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/recettes/': typeof RecettesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/entreprise': typeof EntrepriseRoute
  '/profile': typeof ProfileRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/recipes': typeof DashboardRecipesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/produits/$productId': typeof ProduitsProductIdRoute
  '/recettes/$recipeSlug': typeof RecettesRecipeSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/recettes': typeof RecettesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entreprise': typeof EntrepriseRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recettes': typeof RecettesRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/recipes': typeof DashboardRecipesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/produits/$productId': typeof ProduitsProductIdRoute
  '/recettes/$recipeSlug': typeof RecettesRecipeSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/recettes/': typeof RecettesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/entreprise'
    | '/produits'
    | '/profile'
    | '/recettes'
    | '/dashboard/categories'
    | '/dashboard/contacts'
    | '/dashboard/products'
    | '/dashboard/recipes'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/produits/$productId'
    | '/recettes/$recipeSlug'
    | '/dashboard/'
    | '/produits/'
    | '/recettes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/entreprise'
    | '/profile'
    | '/dashboard/categories'
    | '/dashboard/contacts'
    | '/dashboard/products'
    | '/dashboard/recipes'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/produits/$productId'
    | '/recettes/$recipeSlug'
    | '/dashboard'
    | '/produits'
    | '/recettes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/entreprise'
    | '/produits'
    | '/profile'
    | '/recettes'
    | '/dashboard/categories'
    | '/dashboard/contacts'
    | '/dashboard/products'
    | '/dashboard/recipes'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/produits/$productId'
    | '/recettes/$recipeSlug'
    | '/dashboard/'
    | '/produits/'
    | '/recettes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EntrepriseRoute: typeof EntrepriseRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RecettesRoute: typeof RecettesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes/': {
      id: '/recettes/'
      path: '/'
      fullPath: '/recettes/'
      preLoaderRoute: typeof RecettesIndexRouteImport
      parentRoute: typeof RecettesRoute
    }
    '/produits/': {
      id: '/produits/'
      path: '/'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/recettes/$recipeSlug': {
      id: '/recettes/$recipeSlug'
      path: '/$recipeSlug'
      fullPath: '/recettes/$recipeSlug'
      preLoaderRoute: typeof RecettesRecipeSlugRouteImport
      parentRoute: typeof RecettesRoute
    }
    '/produits/$productId': {
      id: '/produits/$productId'
      path: '/$productId'
      fullPath: '/produits/$productId'
      preLoaderRoute: typeof ProduitsProductIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recipes': {
      id: '/dashboard/recipes'
      path: '/recipes'
      fullPath: '/dashboard/recipes'
      preLoaderRoute: typeof DashboardRecipesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardRecipesRoute: typeof DashboardRecipesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardRecipesRoute: DashboardRecipesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProduitsRouteChildren {
  ProduitsProductIdRoute: typeof ProduitsProductIdRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsProductIdRoute: ProduitsProductIdRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

interface RecettesRouteChildren {
  RecettesRecipeSlugRoute: typeof RecettesRecipeSlugRoute
  RecettesIndexRoute: typeof RecettesIndexRoute
}

const RecettesRouteChildren: RecettesRouteChildren = {
  RecettesRecipeSlugRoute: RecettesRecipeSlugRoute,
  RecettesIndexRoute: RecettesIndexRoute,
}

const RecettesRouteWithChildren = RecettesRoute._addFileChildren(
  RecettesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EntrepriseRoute: EntrepriseRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RecettesRoute: RecettesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
